-- Adicionar novos valores ao Enum de categorias de anexos
ALTER TYPE categoria_anexo ADD VALUE IF NOT EXISTS 'imagens_cftv';
ALTER TYPE categoria_anexo ADD VALUE IF NOT EXISTS 'fotos_avaria';

-- Adicionar novas colunas na tabela operacoes
ALTER TABLE operacoes
ADD COLUMN IF NOT EXISTS cep VARCHAR(20),
ADD COLUMN IF NOT EXISTS quantidade_vagas_moto INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS possui_bicicletario BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS vagas_bicicletario INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS recuo_calcada BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS ticket_manual BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS horario_funcionamento VARCHAR(50),
ADD COLUMN IF NOT EXISTS horario_fechamento VARCHAR(50),
ADD COLUMN IF NOT EXISTS pernoita_veiculo BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS local_guarda_chaves VARCHAR(255),
ADD COLUMN IF NOT EXISTS seguro_sinistro BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS possui_manobra BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS manobra_fora_estacionamento BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS qtd_cancelas INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS qtd_cftv INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_escopo_funcionarios INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS qtd_lideres INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS qtd_operadores_caixa INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS qtd_operadores_estacionamento INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS qtd_asg INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS direito_assiduidade BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS direito_cesta BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS valor_cesta NUMERIC(10, 2) NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS direito_ticket BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS valor_ticket NUMERIC(10, 2) NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS consumo_bobinas BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS bobinas_tipo_modelo VARCHAR(255),
ADD COLUMN IF NOT EXISTS aprovacao_diretoria BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS evidencia_alteracoes TEXT,
ADD COLUMN IF NOT EXISTS data_encerramento DATE,
ADD COLUMN IF NOT EXISTS obs_gerente_operacoes TEXT;
ALTER TYPE categoria_anexo ADD VALUE IF NOT EXISTS 'fotos_prevencao';
